spring:
  application:
    name: eureka-server
server:
  port: 8761
  context-path: /eureka
  eviction-interval-timer-in-ms: 60000
  #清理时间间隔
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:

#    service-url: